/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeGitReleaseDetail200ResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeGitReleaseDetail200ResponseResponse{}

// DescribeGitReleaseDetail200ResponseResponse 公共返回体
type DescribeGitReleaseDetail200ResponseResponse struct {
	Release *Release `json:"Release,omitempty"`
	// 请求id
	RequestId *string `json:"RequestId,omitempty"`
}

// NewDescribeGitReleaseDetail200ResponseResponse instantiates a new DescribeGitReleaseDetail200ResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeGitReleaseDetail200ResponseResponse() *DescribeGitReleaseDetail200ResponseResponse {
	this := DescribeGitReleaseDetail200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// NewDescribeGitReleaseDetail200ResponseResponseWithDefaults instantiates a new DescribeGitReleaseDetail200ResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeGitReleaseDetail200ResponseResponseWithDefaults() *DescribeGitReleaseDetail200ResponseResponse {
	this := DescribeGitReleaseDetail200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *DescribeGitReleaseDetail200ResponseResponse) GetRelease() Release {
	if o == nil || utils.IsNil(o.Release) {
		var ret Release
		return ret
	}
	return *o.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitReleaseDetail200ResponseResponse) GetReleaseOk() (*Release, bool) {
	if o == nil || utils.IsNil(o.Release) {
		return nil, false
	}
	return o.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *DescribeGitReleaseDetail200ResponseResponse) HasRelease() bool {
	if o != nil && !utils.IsNil(o.Release) {
		return true
	}

	return false
}

// SetRelease gets a reference to the given Release and assigns it to the Release field.
func (o *DescribeGitReleaseDetail200ResponseResponse) SetRelease(v Release) {
	o.Release = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *DescribeGitReleaseDetail200ResponseResponse) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitReleaseDetail200ResponseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *DescribeGitReleaseDetail200ResponseResponse) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *DescribeGitReleaseDetail200ResponseResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o DescribeGitReleaseDetail200ResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeGitReleaseDetail200ResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Release) {
		toSerialize["Release"] = o.Release
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["RequestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableDescribeGitReleaseDetail200ResponseResponse struct {
	value *DescribeGitReleaseDetail200ResponseResponse
	isSet bool
}

func (v NullableDescribeGitReleaseDetail200ResponseResponse) Get() *DescribeGitReleaseDetail200ResponseResponse {
	return v.value
}

func (v *NullableDescribeGitReleaseDetail200ResponseResponse) Set(val *DescribeGitReleaseDetail200ResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeGitReleaseDetail200ResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeGitReleaseDetail200ResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeGitReleaseDetail200ResponseResponse(val *DescribeGitReleaseDetail200ResponseResponse) *NullableDescribeGitReleaseDetail200ResponseResponse {
	return &NullableDescribeGitReleaseDetail200ResponseResponse{value: val, isSet: true}
}

func (v NullableDescribeGitReleaseDetail200ResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeGitReleaseDetail200ResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


