/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeCdPipelineConfigs200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeCdPipelineConfigs200Response{}

// DescribeCdPipelineConfigs200Response struct for DescribeCdPipelineConfigs200Response
type DescribeCdPipelineConfigs200Response struct {
	Response *DescribeCdPipelineConfigs200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeCdPipelineConfigs200Response instantiates a new DescribeCdPipelineConfigs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeCdPipelineConfigs200Response() *DescribeCdPipelineConfigs200Response {
	this := DescribeCdPipelineConfigs200Response{}
	return &this
}

// NewDescribeCdPipelineConfigs200ResponseWithDefaults instantiates a new DescribeCdPipelineConfigs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeCdPipelineConfigs200ResponseWithDefaults() *DescribeCdPipelineConfigs200Response {
	this := DescribeCdPipelineConfigs200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeCdPipelineConfigs200Response) GetResponse() DescribeCdPipelineConfigs200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeCdPipelineConfigs200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeCdPipelineConfigs200Response) GetResponseOk() (*DescribeCdPipelineConfigs200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeCdPipelineConfigs200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeCdPipelineConfigs200ResponseResponse and assigns it to the Response field.
func (o *DescribeCdPipelineConfigs200Response) SetResponse(v DescribeCdPipelineConfigs200ResponseResponse) {
	o.Response = &v
}

func (o DescribeCdPipelineConfigs200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeCdPipelineConfigs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeCdPipelineConfigs200Response struct {
	value *DescribeCdPipelineConfigs200Response
	isSet bool
}

func (v NullableDescribeCdPipelineConfigs200Response) Get() *DescribeCdPipelineConfigs200Response {
	return v.value
}

func (v *NullableDescribeCdPipelineConfigs200Response) Set(val *DescribeCdPipelineConfigs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeCdPipelineConfigs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeCdPipelineConfigs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeCdPipelineConfigs200Response(val *DescribeCdPipelineConfigs200Response) *NullableDescribeCdPipelineConfigs200Response {
	return &NullableDescribeCdPipelineConfigs200Response{value: val, isSet: true}
}

func (v NullableDescribeCdPipelineConfigs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeCdPipelineConfigs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


