/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeCdHostServerGroup200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeCdHostServerGroup200Response{}

// DescribeCdHostServerGroup200Response struct for DescribeCdHostServerGroup200Response
type DescribeCdHostServerGroup200Response struct {
	Response *DescribeCdHostServerGroup200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeCdHostServerGroup200Response instantiates a new DescribeCdHostServerGroup200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeCdHostServerGroup200Response() *DescribeCdHostServerGroup200Response {
	this := DescribeCdHostServerGroup200Response{}
	return &this
}

// NewDescribeCdHostServerGroup200ResponseWithDefaults instantiates a new DescribeCdHostServerGroup200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeCdHostServerGroup200ResponseWithDefaults() *DescribeCdHostServerGroup200Response {
	this := DescribeCdHostServerGroup200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeCdHostServerGroup200Response) GetResponse() DescribeCdHostServerGroup200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeCdHostServerGroup200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeCdHostServerGroup200Response) GetResponseOk() (*DescribeCdHostServerGroup200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeCdHostServerGroup200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeCdHostServerGroup200ResponseResponse and assigns it to the Response field.
func (o *DescribeCdHostServerGroup200Response) SetResponse(v DescribeCdHostServerGroup200ResponseResponse) {
	o.Response = &v
}

func (o DescribeCdHostServerGroup200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeCdHostServerGroup200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeCdHostServerGroup200Response struct {
	value *DescribeCdHostServerGroup200Response
	isSet bool
}

func (v NullableDescribeCdHostServerGroup200Response) Get() *DescribeCdHostServerGroup200Response {
	return v.value
}

func (v *NullableDescribeCdHostServerGroup200Response) Set(val *DescribeCdHostServerGroup200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeCdHostServerGroup200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeCdHostServerGroup200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeCdHostServerGroup200Response(val *DescribeCdHostServerGroup200Response) *NullableDescribeCdHostServerGroup200Response {
	return &NullableDescribeCdHostServerGroup200Response{value: val, isSet: true}
}

func (v NullableDescribeCdHostServerGroup200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeCdHostServerGroup200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


