/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeGitBlameInfo200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeGitBlameInfo200Response{}

// DescribeGitBlameInfo200Response struct for DescribeGitBlameInfo200Response
type DescribeGitBlameInfo200Response struct {
	Response *DescribeGitBlameInfo200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeGitBlameInfo200Response instantiates a new DescribeGitBlameInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeGitBlameInfo200Response() *DescribeGitBlameInfo200Response {
	this := DescribeGitBlameInfo200Response{}
	return &this
}

// NewDescribeGitBlameInfo200ResponseWithDefaults instantiates a new DescribeGitBlameInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeGitBlameInfo200ResponseWithDefaults() *DescribeGitBlameInfo200Response {
	this := DescribeGitBlameInfo200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeGitBlameInfo200Response) GetResponse() DescribeGitBlameInfo200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeGitBlameInfo200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitBlameInfo200Response) GetResponseOk() (*DescribeGitBlameInfo200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeGitBlameInfo200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeGitBlameInfo200ResponseResponse and assigns it to the Response field.
func (o *DescribeGitBlameInfo200Response) SetResponse(v DescribeGitBlameInfo200ResponseResponse) {
	o.Response = &v
}

func (o DescribeGitBlameInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeGitBlameInfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeGitBlameInfo200Response struct {
	value *DescribeGitBlameInfo200Response
	isSet bool
}

func (v NullableDescribeGitBlameInfo200Response) Get() *DescribeGitBlameInfo200Response {
	return v.value
}

func (v *NullableDescribeGitBlameInfo200Response) Set(val *DescribeGitBlameInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeGitBlameInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeGitBlameInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeGitBlameInfo200Response(val *DescribeGitBlameInfo200Response) *NullableDescribeGitBlameInfo200Response {
	return &NullableDescribeGitBlameInfo200Response{value: val, isSet: true}
}

func (v NullableDescribeGitBlameInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeGitBlameInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


