/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the ModifyTestCaseSectionRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ModifyTestCaseSectionRequest{}

// ModifyTestCaseSectionRequest struct for ModifyTestCaseSectionRequest
type ModifyTestCaseSectionRequest struct {
	// 分组名称
	Name string `json:"Name"`
	// 父级 ID，默认 0
	ParentId *int32 `json:"ParentId,omitempty"`
	// 项目名称
	ProjectName string `json:"ProjectName"`
	// 分组 ID
	SectionId int32 `json:"SectionId"`
}

type _ModifyTestCaseSectionRequest ModifyTestCaseSectionRequest

// NewModifyTestCaseSectionRequest instantiates a new ModifyTestCaseSectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyTestCaseSectionRequest(name string, projectName string, sectionId int32) *ModifyTestCaseSectionRequest {
	this := ModifyTestCaseSectionRequest{}
	this.Name = name
	this.ProjectName = projectName
	this.SectionId = sectionId
	return &this
}

// NewModifyTestCaseSectionRequestWithDefaults instantiates a new ModifyTestCaseSectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyTestCaseSectionRequestWithDefaults() *ModifyTestCaseSectionRequest {
	this := ModifyTestCaseSectionRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ModifyTestCaseSectionRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ModifyTestCaseSectionRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ModifyTestCaseSectionRequest) SetName(v string) {
	o.Name = v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *ModifyTestCaseSectionRequest) GetParentId() int32 {
	if o == nil || utils.IsNil(o.ParentId) {
		var ret int32
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyTestCaseSectionRequest) GetParentIdOk() (*int32, bool) {
	if o == nil || utils.IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *ModifyTestCaseSectionRequest) HasParentId() bool {
	if o != nil && !utils.IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given int32 and assigns it to the ParentId field.
func (o *ModifyTestCaseSectionRequest) SetParentId(v int32) {
	o.ParentId = &v
}

// GetProjectName returns the ProjectName field value
func (o *ModifyTestCaseSectionRequest) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *ModifyTestCaseSectionRequest) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *ModifyTestCaseSectionRequest) SetProjectName(v string) {
	o.ProjectName = v
}

// GetSectionId returns the SectionId field value
func (o *ModifyTestCaseSectionRequest) GetSectionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SectionId
}

// GetSectionIdOk returns a tuple with the SectionId field value
// and a boolean to check if the value has been set.
func (o *ModifyTestCaseSectionRequest) GetSectionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SectionId, true
}

// SetSectionId sets field value
func (o *ModifyTestCaseSectionRequest) SetSectionId(v int32) {
	o.SectionId = v
}

func (o ModifyTestCaseSectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyTestCaseSectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Name"] = o.Name
	if !utils.IsNil(o.ParentId) {
		toSerialize["ParentId"] = o.ParentId
	}
	toSerialize["ProjectName"] = o.ProjectName
	toSerialize["SectionId"] = o.SectionId
	return toSerialize, nil
}

func (o *ModifyTestCaseSectionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Name",
		"ProjectName",
		"SectionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModifyTestCaseSectionRequest := _ModifyTestCaseSectionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModifyTestCaseSectionRequest)

	if err != nil {
		return err
	}

	*o = ModifyTestCaseSectionRequest(varModifyTestCaseSectionRequest)

	return err
}

type NullableModifyTestCaseSectionRequest struct {
	value *ModifyTestCaseSectionRequest
	isSet bool
}

func (v NullableModifyTestCaseSectionRequest) Get() *ModifyTestCaseSectionRequest {
	return v.value
}

func (v *NullableModifyTestCaseSectionRequest) Set(val *ModifyTestCaseSectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyTestCaseSectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyTestCaseSectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyTestCaseSectionRequest(val *ModifyTestCaseSectionRequest) *NullableModifyTestCaseSectionRequest {
	return &NullableModifyTestCaseSectionRequest{value: val, isSet: true}
}

func (v NullableModifyTestCaseSectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyTestCaseSectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


