/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeIssueCustomFieldLogList200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeIssueCustomFieldLogList200Response{}

// DescribeIssueCustomFieldLogList200Response struct for DescribeIssueCustomFieldLogList200Response
type DescribeIssueCustomFieldLogList200Response struct {
	Response *DescribeIssueCustomFieldLogList200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeIssueCustomFieldLogList200Response instantiates a new DescribeIssueCustomFieldLogList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeIssueCustomFieldLogList200Response() *DescribeIssueCustomFieldLogList200Response {
	this := DescribeIssueCustomFieldLogList200Response{}
	return &this
}

// NewDescribeIssueCustomFieldLogList200ResponseWithDefaults instantiates a new DescribeIssueCustomFieldLogList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeIssueCustomFieldLogList200ResponseWithDefaults() *DescribeIssueCustomFieldLogList200Response {
	this := DescribeIssueCustomFieldLogList200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeIssueCustomFieldLogList200Response) GetResponse() DescribeIssueCustomFieldLogList200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeIssueCustomFieldLogList200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeIssueCustomFieldLogList200Response) GetResponseOk() (*DescribeIssueCustomFieldLogList200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeIssueCustomFieldLogList200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeIssueCustomFieldLogList200ResponseResponse and assigns it to the Response field.
func (o *DescribeIssueCustomFieldLogList200Response) SetResponse(v DescribeIssueCustomFieldLogList200ResponseResponse) {
	o.Response = &v
}

func (o DescribeIssueCustomFieldLogList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeIssueCustomFieldLogList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeIssueCustomFieldLogList200Response struct {
	value *DescribeIssueCustomFieldLogList200Response
	isSet bool
}

func (v NullableDescribeIssueCustomFieldLogList200Response) Get() *DescribeIssueCustomFieldLogList200Response {
	return v.value
}

func (v *NullableDescribeIssueCustomFieldLogList200Response) Set(val *DescribeIssueCustomFieldLogList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeIssueCustomFieldLogList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeIssueCustomFieldLogList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeIssueCustomFieldLogList200Response(val *DescribeIssueCustomFieldLogList200Response) *NullableDescribeIssueCustomFieldLogList200Response {
	return &NullableDescribeIssueCustomFieldLogList200Response{value: val, isSet: true}
}

func (v NullableDescribeIssueCustomFieldLogList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeIssueCustomFieldLogList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


