/*
CODING OPEN API

  

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeIssue200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeIssue200Response{}

// DescribeIssue200Response struct for DescribeIssue200Response
type DescribeIssue200Response struct {
	Response *ModifyIssue200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeIssue200Response instantiates a new DescribeIssue200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeIssue200Response() *DescribeIssue200Response {
	this := DescribeIssue200Response{}
	return &this
}

// NewDescribeIssue200ResponseWithDefaults instantiates a new DescribeIssue200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeIssue200ResponseWithDefaults() *DescribeIssue200Response {
	this := DescribeIssue200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeIssue200Response) GetResponse() ModifyIssue200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret ModifyIssue200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeIssue200Response) GetResponseOk() (*ModifyIssue200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeIssue200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given ModifyIssue200ResponseResponse and assigns it to the Response field.
func (o *DescribeIssue200Response) SetResponse(v ModifyIssue200ResponseResponse) {
	o.Response = &v
}

func (o DescribeIssue200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeIssue200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeIssue200Response struct {
	value *DescribeIssue200Response
	isSet bool
}

func (v NullableDescribeIssue200Response) Get() *DescribeIssue200Response {
	return v.value
}

func (v *NullableDescribeIssue200Response) Set(val *DescribeIssue200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeIssue200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeIssue200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeIssue200Response(val *DescribeIssue200Response) *NullableDescribeIssue200Response {
	return &NullableDescribeIssue200Response{value: val, isSet: true}
}

func (v NullableDescribeIssue200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeIssue200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


