/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeTeamDepots200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeTeamDepots200Response{}

// DescribeTeamDepots200Response struct for DescribeTeamDepots200Response
type DescribeTeamDepots200Response struct {
	Response *DescribeTeamDepots200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeTeamDepots200Response instantiates a new DescribeTeamDepots200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeTeamDepots200Response() *DescribeTeamDepots200Response {
	this := DescribeTeamDepots200Response{}
	return &this
}

// NewDescribeTeamDepots200ResponseWithDefaults instantiates a new DescribeTeamDepots200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeTeamDepots200ResponseWithDefaults() *DescribeTeamDepots200Response {
	this := DescribeTeamDepots200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeTeamDepots200Response) GetResponse() DescribeTeamDepots200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeTeamDepots200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeTeamDepots200Response) GetResponseOk() (*DescribeTeamDepots200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeTeamDepots200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeTeamDepots200ResponseResponse and assigns it to the Response field.
func (o *DescribeTeamDepots200Response) SetResponse(v DescribeTeamDepots200ResponseResponse) {
	o.Response = &v
}

func (o DescribeTeamDepots200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeTeamDepots200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeTeamDepots200Response struct {
	value *DescribeTeamDepots200Response
	isSet bool
}

func (v NullableDescribeTeamDepots200Response) Get() *DescribeTeamDepots200Response {
	return v.value
}

func (v *NullableDescribeTeamDepots200Response) Set(val *DescribeTeamDepots200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeTeamDepots200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeTeamDepots200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeTeamDepots200Response(val *DescribeTeamDepots200Response) *NullableDescribeTeamDepots200Response {
	return &NullableDescribeTeamDepots200Response{value: val, isSet: true}
}

func (v NullableDescribeTeamDepots200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeTeamDepots200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


