/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the ModifyServiceHook200ResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ModifyServiceHook200ResponseResponse{}

// ModifyServiceHook200ResponseResponse 公共返回体
type ModifyServiceHook200ResponseResponse struct {
	ServiceHook *ServiceHook `json:"ServiceHook,omitempty"`
	// 请求id
	RequestId *string `json:"RequestId,omitempty"`
}

// NewModifyServiceHook200ResponseResponse instantiates a new ModifyServiceHook200ResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyServiceHook200ResponseResponse() *ModifyServiceHook200ResponseResponse {
	this := ModifyServiceHook200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// NewModifyServiceHook200ResponseResponseWithDefaults instantiates a new ModifyServiceHook200ResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyServiceHook200ResponseResponseWithDefaults() *ModifyServiceHook200ResponseResponse {
	this := ModifyServiceHook200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// GetServiceHook returns the ServiceHook field value if set, zero value otherwise.
func (o *ModifyServiceHook200ResponseResponse) GetServiceHook() ServiceHook {
	if o == nil || utils.IsNil(o.ServiceHook) {
		var ret ServiceHook
		return ret
	}
	return *o.ServiceHook
}

// GetServiceHookOk returns a tuple with the ServiceHook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyServiceHook200ResponseResponse) GetServiceHookOk() (*ServiceHook, bool) {
	if o == nil || utils.IsNil(o.ServiceHook) {
		return nil, false
	}
	return o.ServiceHook, true
}

// HasServiceHook returns a boolean if a field has been set.
func (o *ModifyServiceHook200ResponseResponse) HasServiceHook() bool {
	if o != nil && !utils.IsNil(o.ServiceHook) {
		return true
	}

	return false
}

// SetServiceHook gets a reference to the given ServiceHook and assigns it to the ServiceHook field.
func (o *ModifyServiceHook200ResponseResponse) SetServiceHook(v ServiceHook) {
	o.ServiceHook = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ModifyServiceHook200ResponseResponse) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyServiceHook200ResponseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ModifyServiceHook200ResponseResponse) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ModifyServiceHook200ResponseResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o ModifyServiceHook200ResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyServiceHook200ResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.ServiceHook) {
		toSerialize["ServiceHook"] = o.ServiceHook
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["RequestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableModifyServiceHook200ResponseResponse struct {
	value *ModifyServiceHook200ResponseResponse
	isSet bool
}

func (v NullableModifyServiceHook200ResponseResponse) Get() *ModifyServiceHook200ResponseResponse {
	return v.value
}

func (v *NullableModifyServiceHook200ResponseResponse) Set(val *ModifyServiceHook200ResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyServiceHook200ResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyServiceHook200ResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyServiceHook200ResponseResponse(val *ModifyServiceHook200ResponseResponse) *NullableModifyServiceHook200ResponseResponse {
	return &NullableModifyServiceHook200ResponseResponse{value: val, isSet: true}
}

func (v NullableModifyServiceHook200ResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyServiceHook200ResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


