/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeCodingCIBuildStep200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeCodingCIBuildStep200Response{}

// DescribeCodingCIBuildStep200Response struct for DescribeCodingCIBuildStep200Response
type DescribeCodingCIBuildStep200Response struct {
	Response *DescribeCodingCIBuildStep200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeCodingCIBuildStep200Response instantiates a new DescribeCodingCIBuildStep200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeCodingCIBuildStep200Response() *DescribeCodingCIBuildStep200Response {
	this := DescribeCodingCIBuildStep200Response{}
	return &this
}

// NewDescribeCodingCIBuildStep200ResponseWithDefaults instantiates a new DescribeCodingCIBuildStep200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeCodingCIBuildStep200ResponseWithDefaults() *DescribeCodingCIBuildStep200Response {
	this := DescribeCodingCIBuildStep200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeCodingCIBuildStep200Response) GetResponse() DescribeCodingCIBuildStep200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeCodingCIBuildStep200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeCodingCIBuildStep200Response) GetResponseOk() (*DescribeCodingCIBuildStep200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeCodingCIBuildStep200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeCodingCIBuildStep200ResponseResponse and assigns it to the Response field.
func (o *DescribeCodingCIBuildStep200Response) SetResponse(v DescribeCodingCIBuildStep200ResponseResponse) {
	o.Response = &v
}

func (o DescribeCodingCIBuildStep200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeCodingCIBuildStep200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeCodingCIBuildStep200Response struct {
	value *DescribeCodingCIBuildStep200Response
	isSet bool
}

func (v NullableDescribeCodingCIBuildStep200Response) Get() *DescribeCodingCIBuildStep200Response {
	return v.value
}

func (v *NullableDescribeCodingCIBuildStep200Response) Set(val *DescribeCodingCIBuildStep200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeCodingCIBuildStep200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeCodingCIBuildStep200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeCodingCIBuildStep200Response(val *DescribeCodingCIBuildStep200Response) *NullableDescribeCodingCIBuildStep200Response {
	return &NullableDescribeCodingCIBuildStep200Response{value: val, isSet: true}
}

func (v NullableDescribeCodingCIBuildStep200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeCodingCIBuildStep200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


