/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeDepotByNameInfo200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeDepotByNameInfo200Response{}

// DescribeDepotByNameInfo200Response struct for DescribeDepotByNameInfo200Response
type DescribeDepotByNameInfo200Response struct {
	Response *DescribeDepotByNameInfo200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeDepotByNameInfo200Response instantiates a new DescribeDepotByNameInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeDepotByNameInfo200Response() *DescribeDepotByNameInfo200Response {
	this := DescribeDepotByNameInfo200Response{}
	return &this
}

// NewDescribeDepotByNameInfo200ResponseWithDefaults instantiates a new DescribeDepotByNameInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeDepotByNameInfo200ResponseWithDefaults() *DescribeDepotByNameInfo200Response {
	this := DescribeDepotByNameInfo200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeDepotByNameInfo200Response) GetResponse() DescribeDepotByNameInfo200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeDepotByNameInfo200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeDepotByNameInfo200Response) GetResponseOk() (*DescribeDepotByNameInfo200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeDepotByNameInfo200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeDepotByNameInfo200ResponseResponse and assigns it to the Response field.
func (o *DescribeDepotByNameInfo200Response) SetResponse(v DescribeDepotByNameInfo200ResponseResponse) {
	o.Response = &v
}

func (o DescribeDepotByNameInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeDepotByNameInfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeDepotByNameInfo200Response struct {
	value *DescribeDepotByNameInfo200Response
	isSet bool
}

func (v NullableDescribeDepotByNameInfo200Response) Get() *DescribeDepotByNameInfo200Response {
	return v.value
}

func (v *NullableDescribeDepotByNameInfo200Response) Set(val *DescribeDepotByNameInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeDepotByNameInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeDepotByNameInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeDepotByNameInfo200Response(val *DescribeDepotByNameInfo200Response) *NullableDescribeDepotByNameInfo200Response {
	return &NullableDescribeDepotByNameInfo200Response{value: val, isSet: true}
}

func (v NullableDescribeDepotByNameInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeDepotByNameInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


