/*
CODING OPEN API

  

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeGitMergeRequestsBySha200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeGitMergeRequestsBySha200Response{}

// DescribeGitMergeRequestsBySha200Response struct for DescribeGitMergeRequestsBySha200Response
type DescribeGitMergeRequestsBySha200Response struct {
	Response *DescribeGitMergeRequestsBySha200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeGitMergeRequestsBySha200Response instantiates a new DescribeGitMergeRequestsBySha200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeGitMergeRequestsBySha200Response() *DescribeGitMergeRequestsBySha200Response {
	this := DescribeGitMergeRequestsBySha200Response{}
	return &this
}

// NewDescribeGitMergeRequestsBySha200ResponseWithDefaults instantiates a new DescribeGitMergeRequestsBySha200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeGitMergeRequestsBySha200ResponseWithDefaults() *DescribeGitMergeRequestsBySha200Response {
	this := DescribeGitMergeRequestsBySha200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeGitMergeRequestsBySha200Response) GetResponse() DescribeGitMergeRequestsBySha200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeGitMergeRequestsBySha200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitMergeRequestsBySha200Response) GetResponseOk() (*DescribeGitMergeRequestsBySha200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeGitMergeRequestsBySha200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeGitMergeRequestsBySha200ResponseResponse and assigns it to the Response field.
func (o *DescribeGitMergeRequestsBySha200Response) SetResponse(v DescribeGitMergeRequestsBySha200ResponseResponse) {
	o.Response = &v
}

func (o DescribeGitMergeRequestsBySha200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeGitMergeRequestsBySha200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeGitMergeRequestsBySha200Response struct {
	value *DescribeGitMergeRequestsBySha200Response
	isSet bool
}

func (v NullableDescribeGitMergeRequestsBySha200Response) Get() *DescribeGitMergeRequestsBySha200Response {
	return v.value
}

func (v *NullableDescribeGitMergeRequestsBySha200Response) Set(val *DescribeGitMergeRequestsBySha200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeGitMergeRequestsBySha200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeGitMergeRequestsBySha200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeGitMergeRequestsBySha200Response(val *DescribeGitMergeRequestsBySha200Response) *NullableDescribeGitMergeRequestsBySha200Response {
	return &NullableDescribeGitMergeRequestsBySha200Response{value: val, isSet: true}
}

func (v NullableDescribeGitMergeRequestsBySha200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeGitMergeRequestsBySha200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


