/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the ModifyArtifactPropertiesRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ModifyArtifactPropertiesRequest{}

// ModifyArtifactPropertiesRequest struct for ModifyArtifactPropertiesRequest
type ModifyArtifactPropertiesRequest struct {
	// 包名
	Package string `json:"Package"`
	// 版本号
	PackageVersion string `json:"PackageVersion"`
	// 项目 ID
	ProjectId int32 `json:"ProjectId"`
	// 属性列表
	PropertySet []ArtifactPropertyBean `json:"PropertySet"`
	// 仓库名
	Repository string `json:"Repository"`
}

type _ModifyArtifactPropertiesRequest ModifyArtifactPropertiesRequest

// NewModifyArtifactPropertiesRequest instantiates a new ModifyArtifactPropertiesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyArtifactPropertiesRequest(package_ string, packageVersion string, projectId int32, propertySet []ArtifactPropertyBean, repository string) *ModifyArtifactPropertiesRequest {
	this := ModifyArtifactPropertiesRequest{}
	this.Package = package_
	this.PackageVersion = packageVersion
	this.ProjectId = projectId
	this.PropertySet = propertySet
	this.Repository = repository
	return &this
}

// NewModifyArtifactPropertiesRequestWithDefaults instantiates a new ModifyArtifactPropertiesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyArtifactPropertiesRequestWithDefaults() *ModifyArtifactPropertiesRequest {
	this := ModifyArtifactPropertiesRequest{}
	return &this
}

// GetPackage returns the Package field value
func (o *ModifyArtifactPropertiesRequest) GetPackage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Package
}

// GetPackageOk returns a tuple with the Package field value
// and a boolean to check if the value has been set.
func (o *ModifyArtifactPropertiesRequest) GetPackageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Package, true
}

// SetPackage sets field value
func (o *ModifyArtifactPropertiesRequest) SetPackage(v string) {
	o.Package = v
}

// GetPackageVersion returns the PackageVersion field value
func (o *ModifyArtifactPropertiesRequest) GetPackageVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PackageVersion
}

// GetPackageVersionOk returns a tuple with the PackageVersion field value
// and a boolean to check if the value has been set.
func (o *ModifyArtifactPropertiesRequest) GetPackageVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PackageVersion, true
}

// SetPackageVersion sets field value
func (o *ModifyArtifactPropertiesRequest) SetPackageVersion(v string) {
	o.PackageVersion = v
}

// GetProjectId returns the ProjectId field value
func (o *ModifyArtifactPropertiesRequest) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ModifyArtifactPropertiesRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ModifyArtifactPropertiesRequest) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetPropertySet returns the PropertySet field value
func (o *ModifyArtifactPropertiesRequest) GetPropertySet() []ArtifactPropertyBean {
	if o == nil {
		var ret []ArtifactPropertyBean
		return ret
	}

	return o.PropertySet
}

// GetPropertySetOk returns a tuple with the PropertySet field value
// and a boolean to check if the value has been set.
func (o *ModifyArtifactPropertiesRequest) GetPropertySetOk() ([]ArtifactPropertyBean, bool) {
	if o == nil {
		return nil, false
	}
	return o.PropertySet, true
}

// SetPropertySet sets field value
func (o *ModifyArtifactPropertiesRequest) SetPropertySet(v []ArtifactPropertyBean) {
	o.PropertySet = v
}

// GetRepository returns the Repository field value
func (o *ModifyArtifactPropertiesRequest) GetRepository() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value
// and a boolean to check if the value has been set.
func (o *ModifyArtifactPropertiesRequest) GetRepositoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repository, true
}

// SetRepository sets field value
func (o *ModifyArtifactPropertiesRequest) SetRepository(v string) {
	o.Repository = v
}

func (o ModifyArtifactPropertiesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyArtifactPropertiesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Package"] = o.Package
	toSerialize["PackageVersion"] = o.PackageVersion
	toSerialize["ProjectId"] = o.ProjectId
	toSerialize["PropertySet"] = o.PropertySet
	toSerialize["Repository"] = o.Repository
	return toSerialize, nil
}

func (o *ModifyArtifactPropertiesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Package",
		"PackageVersion",
		"ProjectId",
		"PropertySet",
		"Repository",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModifyArtifactPropertiesRequest := _ModifyArtifactPropertiesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModifyArtifactPropertiesRequest)

	if err != nil {
		return err
	}

	*o = ModifyArtifactPropertiesRequest(varModifyArtifactPropertiesRequest)

	return err
}

type NullableModifyArtifactPropertiesRequest struct {
	value *ModifyArtifactPropertiesRequest
	isSet bool
}

func (v NullableModifyArtifactPropertiesRequest) Get() *ModifyArtifactPropertiesRequest {
	return v.value
}

func (v *NullableModifyArtifactPropertiesRequest) Set(val *ModifyArtifactPropertiesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyArtifactPropertiesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyArtifactPropertiesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyArtifactPropertiesRequest(val *ModifyArtifactPropertiesRequest) *NullableModifyArtifactPropertiesRequest {
	return &NullableModifyArtifactPropertiesRequest{value: val, isSet: true}
}

func (v NullableModifyArtifactPropertiesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyArtifactPropertiesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


