/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeProjectRolesRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeProjectRolesRequest{}

// DescribeProjectRolesRequest struct for DescribeProjectRolesRequest
type DescribeProjectRolesRequest struct {
	// 项目Id
	ProjectId int32 `json:"ProjectId"`
}

type _DescribeProjectRolesRequest DescribeProjectRolesRequest

// NewDescribeProjectRolesRequest instantiates a new DescribeProjectRolesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeProjectRolesRequest(projectId int32) *DescribeProjectRolesRequest {
	this := DescribeProjectRolesRequest{}
	this.ProjectId = projectId
	return &this
}

// NewDescribeProjectRolesRequestWithDefaults instantiates a new DescribeProjectRolesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeProjectRolesRequestWithDefaults() *DescribeProjectRolesRequest {
	this := DescribeProjectRolesRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *DescribeProjectRolesRequest) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *DescribeProjectRolesRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *DescribeProjectRolesRequest) SetProjectId(v int32) {
	o.ProjectId = v
}

func (o DescribeProjectRolesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeProjectRolesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ProjectId"] = o.ProjectId
	return toSerialize, nil
}

func (o *DescribeProjectRolesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ProjectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDescribeProjectRolesRequest := _DescribeProjectRolesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDescribeProjectRolesRequest)

	if err != nil {
		return err
	}

	*o = DescribeProjectRolesRequest(varDescribeProjectRolesRequest)

	return err
}

type NullableDescribeProjectRolesRequest struct {
	value *DescribeProjectRolesRequest
	isSet bool
}

func (v NullableDescribeProjectRolesRequest) Get() *DescribeProjectRolesRequest {
	return v.value
}

func (v *NullableDescribeProjectRolesRequest) Set(val *DescribeProjectRolesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeProjectRolesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeProjectRolesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeProjectRolesRequest(val *DescribeProjectRolesRequest) *NullableDescribeProjectRolesRequest {
	return &NullableDescribeProjectRolesRequest{value: val, isSet: true}
}

func (v NullableDescribeProjectRolesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeProjectRolesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


