/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeGitBlameInfo200ResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeGitBlameInfo200ResponseResponse{}

// DescribeGitBlameInfo200ResponseResponse 公共返回体
type DescribeGitBlameInfo200ResponseResponse struct {
	// 提交信息
	Info []CommitInfo `json:"Info,omitempty"`
	// 请求id
	RequestId *string `json:"RequestId,omitempty"`
}

// NewDescribeGitBlameInfo200ResponseResponse instantiates a new DescribeGitBlameInfo200ResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeGitBlameInfo200ResponseResponse() *DescribeGitBlameInfo200ResponseResponse {
	this := DescribeGitBlameInfo200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// NewDescribeGitBlameInfo200ResponseResponseWithDefaults instantiates a new DescribeGitBlameInfo200ResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeGitBlameInfo200ResponseResponseWithDefaults() *DescribeGitBlameInfo200ResponseResponse {
	this := DescribeGitBlameInfo200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// GetInfo returns the Info field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DescribeGitBlameInfo200ResponseResponse) GetInfo() []CommitInfo {
	if o == nil {
		var ret []CommitInfo
		return ret
	}
	return o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DescribeGitBlameInfo200ResponseResponse) GetInfoOk() ([]CommitInfo, bool) {
	if o == nil || utils.IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *DescribeGitBlameInfo200ResponseResponse) HasInfo() bool {
	if o != nil && !utils.IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given []CommitInfo and assigns it to the Info field.
func (o *DescribeGitBlameInfo200ResponseResponse) SetInfo(v []CommitInfo) {
	o.Info = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *DescribeGitBlameInfo200ResponseResponse) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitBlameInfo200ResponseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *DescribeGitBlameInfo200ResponseResponse) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *DescribeGitBlameInfo200ResponseResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o DescribeGitBlameInfo200ResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeGitBlameInfo200ResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Info != nil {
		toSerialize["Info"] = o.Info
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["RequestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableDescribeGitBlameInfo200ResponseResponse struct {
	value *DescribeGitBlameInfo200ResponseResponse
	isSet bool
}

func (v NullableDescribeGitBlameInfo200ResponseResponse) Get() *DescribeGitBlameInfo200ResponseResponse {
	return v.value
}

func (v *NullableDescribeGitBlameInfo200ResponseResponse) Set(val *DescribeGitBlameInfo200ResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeGitBlameInfo200ResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeGitBlameInfo200ResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeGitBlameInfo200ResponseResponse(val *DescribeGitBlameInfo200ResponseResponse) *NullableDescribeGitBlameInfo200ResponseResponse {
	return &NullableDescribeGitBlameInfo200ResponseResponse{value: val, isSet: true}
}

func (v NullableDescribeGitBlameInfo200ResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeGitBlameInfo200ResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


