/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeIssueCustomFieldLogListRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeIssueCustomFieldLogListRequest{}

// DescribeIssueCustomFieldLogListRequest struct for DescribeIssueCustomFieldLogListRequest
type DescribeIssueCustomFieldLogListRequest struct {
	// 自定义属性名称
	FieldName string `json:"FieldName"`
	// 事项编号
	IssueCode int64 `json:"IssueCode"`
	// 项目名称
	ProjectName string `json:"ProjectName"`
}

type _DescribeIssueCustomFieldLogListRequest DescribeIssueCustomFieldLogListRequest

// NewDescribeIssueCustomFieldLogListRequest instantiates a new DescribeIssueCustomFieldLogListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeIssueCustomFieldLogListRequest(fieldName string, issueCode int64, projectName string) *DescribeIssueCustomFieldLogListRequest {
	this := DescribeIssueCustomFieldLogListRequest{}
	this.FieldName = fieldName
	this.IssueCode = issueCode
	this.ProjectName = projectName
	return &this
}

// NewDescribeIssueCustomFieldLogListRequestWithDefaults instantiates a new DescribeIssueCustomFieldLogListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeIssueCustomFieldLogListRequestWithDefaults() *DescribeIssueCustomFieldLogListRequest {
	this := DescribeIssueCustomFieldLogListRequest{}
	return &this
}

// GetFieldName returns the FieldName field value
func (o *DescribeIssueCustomFieldLogListRequest) GetFieldName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value
// and a boolean to check if the value has been set.
func (o *DescribeIssueCustomFieldLogListRequest) GetFieldNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldName, true
}

// SetFieldName sets field value
func (o *DescribeIssueCustomFieldLogListRequest) SetFieldName(v string) {
	o.FieldName = v
}

// GetIssueCode returns the IssueCode field value
func (o *DescribeIssueCustomFieldLogListRequest) GetIssueCode() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.IssueCode
}

// GetIssueCodeOk returns a tuple with the IssueCode field value
// and a boolean to check if the value has been set.
func (o *DescribeIssueCustomFieldLogListRequest) GetIssueCodeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssueCode, true
}

// SetIssueCode sets field value
func (o *DescribeIssueCustomFieldLogListRequest) SetIssueCode(v int64) {
	o.IssueCode = v
}

// GetProjectName returns the ProjectName field value
func (o *DescribeIssueCustomFieldLogListRequest) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *DescribeIssueCustomFieldLogListRequest) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *DescribeIssueCustomFieldLogListRequest) SetProjectName(v string) {
	o.ProjectName = v
}

func (o DescribeIssueCustomFieldLogListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeIssueCustomFieldLogListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["FieldName"] = o.FieldName
	toSerialize["IssueCode"] = o.IssueCode
	toSerialize["ProjectName"] = o.ProjectName
	return toSerialize, nil
}

func (o *DescribeIssueCustomFieldLogListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"FieldName",
		"IssueCode",
		"ProjectName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDescribeIssueCustomFieldLogListRequest := _DescribeIssueCustomFieldLogListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDescribeIssueCustomFieldLogListRequest)

	if err != nil {
		return err
	}

	*o = DescribeIssueCustomFieldLogListRequest(varDescribeIssueCustomFieldLogListRequest)

	return err
}

type NullableDescribeIssueCustomFieldLogListRequest struct {
	value *DescribeIssueCustomFieldLogListRequest
	isSet bool
}

func (v NullableDescribeIssueCustomFieldLogListRequest) Get() *DescribeIssueCustomFieldLogListRequest {
	return v.value
}

func (v *NullableDescribeIssueCustomFieldLogListRequest) Set(val *DescribeIssueCustomFieldLogListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeIssueCustomFieldLogListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeIssueCustomFieldLogListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeIssueCustomFieldLogListRequest(val *DescribeIssueCustomFieldLogListRequest) *NullableDescribeIssueCustomFieldLogListRequest {
	return &NullableDescribeIssueCustomFieldLogListRequest{value: val, isSet: true}
}

func (v NullableDescribeIssueCustomFieldLogListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeIssueCustomFieldLogListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


