/*
CODING OPEN API

  

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DeleteProgramMemberPolicy200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DeleteProgramMemberPolicy200Response{}

// DeleteProgramMemberPolicy200Response struct for DeleteProgramMemberPolicy200Response
type DeleteProgramMemberPolicy200Response struct {
	Response *DeleteProgramMemberPolicy200ResponseResponse `json:"Response,omitempty"`
}

// NewDeleteProgramMemberPolicy200Response instantiates a new DeleteProgramMemberPolicy200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteProgramMemberPolicy200Response() *DeleteProgramMemberPolicy200Response {
	this := DeleteProgramMemberPolicy200Response{}
	return &this
}

// NewDeleteProgramMemberPolicy200ResponseWithDefaults instantiates a new DeleteProgramMemberPolicy200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteProgramMemberPolicy200ResponseWithDefaults() *DeleteProgramMemberPolicy200Response {
	this := DeleteProgramMemberPolicy200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DeleteProgramMemberPolicy200Response) GetResponse() DeleteProgramMemberPolicy200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DeleteProgramMemberPolicy200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteProgramMemberPolicy200Response) GetResponseOk() (*DeleteProgramMemberPolicy200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DeleteProgramMemberPolicy200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DeleteProgramMemberPolicy200ResponseResponse and assigns it to the Response field.
func (o *DeleteProgramMemberPolicy200Response) SetResponse(v DeleteProgramMemberPolicy200ResponseResponse) {
	o.Response = &v
}

func (o DeleteProgramMemberPolicy200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteProgramMemberPolicy200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDeleteProgramMemberPolicy200Response struct {
	value *DeleteProgramMemberPolicy200Response
	isSet bool
}

func (v NullableDeleteProgramMemberPolicy200Response) Get() *DeleteProgramMemberPolicy200Response {
	return v.value
}

func (v *NullableDeleteProgramMemberPolicy200Response) Set(val *DeleteProgramMemberPolicy200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteProgramMemberPolicy200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteProgramMemberPolicy200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteProgramMemberPolicy200Response(val *DeleteProgramMemberPolicy200Response) *NullableDeleteProgramMemberPolicy200Response {
	return &NullableDeleteProgramMemberPolicy200Response{value: val, isSet: true}
}

func (v NullableDeleteProgramMemberPolicy200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteProgramMemberPolicy200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


