/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the PolicyDocument type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &PolicyDocument{}

// PolicyDocument 权限组 Document
type PolicyDocument struct {
	// 授权句柄
	Statement []PolicyStatement `json:"Statement"`
}

type _PolicyDocument PolicyDocument

// NewPolicyDocument instantiates a new PolicyDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyDocument(statement []PolicyStatement) *PolicyDocument {
	this := PolicyDocument{}
	this.Statement = statement
	return &this
}

// NewPolicyDocumentWithDefaults instantiates a new PolicyDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyDocumentWithDefaults() *PolicyDocument {
	this := PolicyDocument{}
	return &this
}

// GetStatement returns the Statement field value
func (o *PolicyDocument) GetStatement() []PolicyStatement {
	if o == nil {
		var ret []PolicyStatement
		return ret
	}

	return o.Statement
}

// GetStatementOk returns a tuple with the Statement field value
// and a boolean to check if the value has been set.
func (o *PolicyDocument) GetStatementOk() ([]PolicyStatement, bool) {
	if o == nil {
		return nil, false
	}
	return o.Statement, true
}

// SetStatement sets field value
func (o *PolicyDocument) SetStatement(v []PolicyStatement) {
	o.Statement = v
}

func (o PolicyDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Statement"] = o.Statement
	return toSerialize, nil
}

func (o *PolicyDocument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Statement",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyDocument := _PolicyDocument{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyDocument)

	if err != nil {
		return err
	}

	*o = PolicyDocument(varPolicyDocument)

	return err
}

type NullablePolicyDocument struct {
	value *PolicyDocument
	isSet bool
}

func (v NullablePolicyDocument) Get() *PolicyDocument {
	return v.value
}

func (v *NullablePolicyDocument) Set(val *PolicyDocument) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyDocument) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyDocument(val *PolicyDocument) *NullablePolicyDocument {
	return &NullablePolicyDocument{value: val, isSet: true}
}

func (v NullablePolicyDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


