/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the CreateGitProtectedTagRuleRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CreateGitProtectedTagRuleRequest{}

// CreateGitProtectedTagRuleRequest struct for CreateGitProtectedTagRuleRequest
type CreateGitProtectedTagRuleRequest struct {
	// 仓库 Id
	DepotId int64 `json:"DepotId"`
	// 仓库路径，与仓库ID二选一
	DepotPath *string `json:"DepotPath,omitempty"`
	// 保护规则
	Rule string `json:"Rule"`
}

type _CreateGitProtectedTagRuleRequest CreateGitProtectedTagRuleRequest

// NewCreateGitProtectedTagRuleRequest instantiates a new CreateGitProtectedTagRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGitProtectedTagRuleRequest(depotId int64, rule string) *CreateGitProtectedTagRuleRequest {
	this := CreateGitProtectedTagRuleRequest{}
	this.DepotId = depotId
	this.Rule = rule
	return &this
}

// NewCreateGitProtectedTagRuleRequestWithDefaults instantiates a new CreateGitProtectedTagRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGitProtectedTagRuleRequestWithDefaults() *CreateGitProtectedTagRuleRequest {
	this := CreateGitProtectedTagRuleRequest{}
	return &this
}

// GetDepotId returns the DepotId field value
func (o *CreateGitProtectedTagRuleRequest) GetDepotId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DepotId
}

// GetDepotIdOk returns a tuple with the DepotId field value
// and a boolean to check if the value has been set.
func (o *CreateGitProtectedTagRuleRequest) GetDepotIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepotId, true
}

// SetDepotId sets field value
func (o *CreateGitProtectedTagRuleRequest) SetDepotId(v int64) {
	o.DepotId = v
}

// GetDepotPath returns the DepotPath field value if set, zero value otherwise.
func (o *CreateGitProtectedTagRuleRequest) GetDepotPath() string {
	if o == nil || utils.IsNil(o.DepotPath) {
		var ret string
		return ret
	}
	return *o.DepotPath
}

// GetDepotPathOk returns a tuple with the DepotPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGitProtectedTagRuleRequest) GetDepotPathOk() (*string, bool) {
	if o == nil || utils.IsNil(o.DepotPath) {
		return nil, false
	}
	return o.DepotPath, true
}

// HasDepotPath returns a boolean if a field has been set.
func (o *CreateGitProtectedTagRuleRequest) HasDepotPath() bool {
	if o != nil && !utils.IsNil(o.DepotPath) {
		return true
	}

	return false
}

// SetDepotPath gets a reference to the given string and assigns it to the DepotPath field.
func (o *CreateGitProtectedTagRuleRequest) SetDepotPath(v string) {
	o.DepotPath = &v
}

// GetRule returns the Rule field value
func (o *CreateGitProtectedTagRuleRequest) GetRule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rule
}

// GetRuleOk returns a tuple with the Rule field value
// and a boolean to check if the value has been set.
func (o *CreateGitProtectedTagRuleRequest) GetRuleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rule, true
}

// SetRule sets field value
func (o *CreateGitProtectedTagRuleRequest) SetRule(v string) {
	o.Rule = v
}

func (o CreateGitProtectedTagRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGitProtectedTagRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["DepotId"] = o.DepotId
	if !utils.IsNil(o.DepotPath) {
		toSerialize["DepotPath"] = o.DepotPath
	}
	toSerialize["Rule"] = o.Rule
	return toSerialize, nil
}

func (o *CreateGitProtectedTagRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"DepotId",
		"Rule",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateGitProtectedTagRuleRequest := _CreateGitProtectedTagRuleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateGitProtectedTagRuleRequest)

	if err != nil {
		return err
	}

	*o = CreateGitProtectedTagRuleRequest(varCreateGitProtectedTagRuleRequest)

	return err
}

type NullableCreateGitProtectedTagRuleRequest struct {
	value *CreateGitProtectedTagRuleRequest
	isSet bool
}

func (v NullableCreateGitProtectedTagRuleRequest) Get() *CreateGitProtectedTagRuleRequest {
	return v.value
}

func (v *NullableCreateGitProtectedTagRuleRequest) Set(val *CreateGitProtectedTagRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGitProtectedTagRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGitProtectedTagRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGitProtectedTagRuleRequest(val *CreateGitProtectedTagRuleRequest) *NullableCreateGitProtectedTagRuleRequest {
	return &NullableCreateGitProtectedTagRuleRequest{value: val, isSet: true}
}

func (v NullableCreateGitProtectedTagRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGitProtectedTagRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


