/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeTeam200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeTeam200Response{}

// DescribeTeam200Response struct for DescribeTeam200Response
type DescribeTeam200Response struct {
	Response *DescribeTeam200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeTeam200Response instantiates a new DescribeTeam200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeTeam200Response() *DescribeTeam200Response {
	this := DescribeTeam200Response{}
	return &this
}

// NewDescribeTeam200ResponseWithDefaults instantiates a new DescribeTeam200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeTeam200ResponseWithDefaults() *DescribeTeam200Response {
	this := DescribeTeam200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeTeam200Response) GetResponse() DescribeTeam200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeTeam200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeTeam200Response) GetResponseOk() (*DescribeTeam200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeTeam200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeTeam200ResponseResponse and assigns it to the Response field.
func (o *DescribeTeam200Response) SetResponse(v DescribeTeam200ResponseResponse) {
	o.Response = &v
}

func (o DescribeTeam200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeTeam200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeTeam200Response struct {
	value *DescribeTeam200Response
	isSet bool
}

func (v NullableDescribeTeam200Response) Get() *DescribeTeam200Response {
	return v.value
}

func (v *NullableDescribeTeam200Response) Set(val *DescribeTeam200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeTeam200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeTeam200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeTeam200Response(val *DescribeTeam200Response) *NullableDescribeTeam200Response {
	return &NullableDescribeTeam200Response{value: val, isSet: true}
}

func (v NullableDescribeTeam200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeTeam200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


