/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeSingeMergeRequestNotesRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeSingeMergeRequestNotesRequest{}

// DescribeSingeMergeRequestNotesRequest struct for DescribeSingeMergeRequestNotesRequest
type DescribeSingeMergeRequestNotesRequest struct {
	// 仓库路径
	DepotPath string `json:"DepotPath"`
	// 合并请求的Iid
	MergeId int32 `json:"MergeId"`
}

type _DescribeSingeMergeRequestNotesRequest DescribeSingeMergeRequestNotesRequest

// NewDescribeSingeMergeRequestNotesRequest instantiates a new DescribeSingeMergeRequestNotesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeSingeMergeRequestNotesRequest(depotPath string, mergeId int32) *DescribeSingeMergeRequestNotesRequest {
	this := DescribeSingeMergeRequestNotesRequest{}
	this.DepotPath = depotPath
	this.MergeId = mergeId
	return &this
}

// NewDescribeSingeMergeRequestNotesRequestWithDefaults instantiates a new DescribeSingeMergeRequestNotesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeSingeMergeRequestNotesRequestWithDefaults() *DescribeSingeMergeRequestNotesRequest {
	this := DescribeSingeMergeRequestNotesRequest{}
	return &this
}

// GetDepotPath returns the DepotPath field value
func (o *DescribeSingeMergeRequestNotesRequest) GetDepotPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DepotPath
}

// GetDepotPathOk returns a tuple with the DepotPath field value
// and a boolean to check if the value has been set.
func (o *DescribeSingeMergeRequestNotesRequest) GetDepotPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepotPath, true
}

// SetDepotPath sets field value
func (o *DescribeSingeMergeRequestNotesRequest) SetDepotPath(v string) {
	o.DepotPath = v
}

// GetMergeId returns the MergeId field value
func (o *DescribeSingeMergeRequestNotesRequest) GetMergeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MergeId
}

// GetMergeIdOk returns a tuple with the MergeId field value
// and a boolean to check if the value has been set.
func (o *DescribeSingeMergeRequestNotesRequest) GetMergeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MergeId, true
}

// SetMergeId sets field value
func (o *DescribeSingeMergeRequestNotesRequest) SetMergeId(v int32) {
	o.MergeId = v
}

func (o DescribeSingeMergeRequestNotesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeSingeMergeRequestNotesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["DepotPath"] = o.DepotPath
	toSerialize["MergeId"] = o.MergeId
	return toSerialize, nil
}

func (o *DescribeSingeMergeRequestNotesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"DepotPath",
		"MergeId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDescribeSingeMergeRequestNotesRequest := _DescribeSingeMergeRequestNotesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDescribeSingeMergeRequestNotesRequest)

	if err != nil {
		return err
	}

	*o = DescribeSingeMergeRequestNotesRequest(varDescribeSingeMergeRequestNotesRequest)

	return err
}

type NullableDescribeSingeMergeRequestNotesRequest struct {
	value *DescribeSingeMergeRequestNotesRequest
	isSet bool
}

func (v NullableDescribeSingeMergeRequestNotesRequest) Get() *DescribeSingeMergeRequestNotesRequest {
	return v.value
}

func (v *NullableDescribeSingeMergeRequestNotesRequest) Set(val *DescribeSingeMergeRequestNotesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeSingeMergeRequestNotesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeSingeMergeRequestNotesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeSingeMergeRequestNotesRequest(val *DescribeSingeMergeRequestNotesRequest) *NullableDescribeSingeMergeRequestNotesRequest {
	return &NullableDescribeSingeMergeRequestNotesRequest{value: val, isSet: true}
}

func (v NullableDescribeSingeMergeRequestNotesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeSingeMergeRequestNotesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


