/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DeleteGitMergedBranchesRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DeleteGitMergedBranchesRequest{}

// DeleteGitMergedBranchesRequest struct for DeleteGitMergedBranchesRequest
type DeleteGitMergedBranchesRequest struct {
	// 仓库 ID
	DepotId int64 `json:"DepotId"`
	// 仓库路径，DepotId与DepotPath二选一即可
	DepotPath string `json:"DepotPath"`
}

type _DeleteGitMergedBranchesRequest DeleteGitMergedBranchesRequest

// NewDeleteGitMergedBranchesRequest instantiates a new DeleteGitMergedBranchesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteGitMergedBranchesRequest(depotId int64, depotPath string) *DeleteGitMergedBranchesRequest {
	this := DeleteGitMergedBranchesRequest{}
	this.DepotId = depotId
	this.DepotPath = depotPath
	return &this
}

// NewDeleteGitMergedBranchesRequestWithDefaults instantiates a new DeleteGitMergedBranchesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteGitMergedBranchesRequestWithDefaults() *DeleteGitMergedBranchesRequest {
	this := DeleteGitMergedBranchesRequest{}
	return &this
}

// GetDepotId returns the DepotId field value
func (o *DeleteGitMergedBranchesRequest) GetDepotId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DepotId
}

// GetDepotIdOk returns a tuple with the DepotId field value
// and a boolean to check if the value has been set.
func (o *DeleteGitMergedBranchesRequest) GetDepotIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepotId, true
}

// SetDepotId sets field value
func (o *DeleteGitMergedBranchesRequest) SetDepotId(v int64) {
	o.DepotId = v
}

// GetDepotPath returns the DepotPath field value
func (o *DeleteGitMergedBranchesRequest) GetDepotPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DepotPath
}

// GetDepotPathOk returns a tuple with the DepotPath field value
// and a boolean to check if the value has been set.
func (o *DeleteGitMergedBranchesRequest) GetDepotPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepotPath, true
}

// SetDepotPath sets field value
func (o *DeleteGitMergedBranchesRequest) SetDepotPath(v string) {
	o.DepotPath = v
}

func (o DeleteGitMergedBranchesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteGitMergedBranchesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["DepotId"] = o.DepotId
	toSerialize["DepotPath"] = o.DepotPath
	return toSerialize, nil
}

func (o *DeleteGitMergedBranchesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"DepotId",
		"DepotPath",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteGitMergedBranchesRequest := _DeleteGitMergedBranchesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteGitMergedBranchesRequest)

	if err != nil {
		return err
	}

	*o = DeleteGitMergedBranchesRequest(varDeleteGitMergedBranchesRequest)

	return err
}

type NullableDeleteGitMergedBranchesRequest struct {
	value *DeleteGitMergedBranchesRequest
	isSet bool
}

func (v NullableDeleteGitMergedBranchesRequest) Get() *DeleteGitMergedBranchesRequest {
	return v.value
}

func (v *NullableDeleteGitMergedBranchesRequest) Set(val *DeleteGitMergedBranchesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteGitMergedBranchesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteGitMergedBranchesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteGitMergedBranchesRequest(val *DeleteGitMergedBranchesRequest) *NullableDeleteGitMergedBranchesRequest {
	return &NullableDeleteGitMergedBranchesRequest{value: val, isSet: true}
}

func (v NullableDeleteGitMergedBranchesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteGitMergedBranchesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


