/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeGitBranchesBySha200ResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeGitBranchesBySha200ResponseResponse{}

// DescribeGitBranchesBySha200ResponseResponse 公共返回体
type DescribeGitBranchesBySha200ResponseResponse struct {
	// ref信息列表
	Refs []RefInfo `json:"Refs,omitempty"`
	// 请求id
	RequestId *string `json:"RequestId,omitempty"`
}

// NewDescribeGitBranchesBySha200ResponseResponse instantiates a new DescribeGitBranchesBySha200ResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeGitBranchesBySha200ResponseResponse() *DescribeGitBranchesBySha200ResponseResponse {
	this := DescribeGitBranchesBySha200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// NewDescribeGitBranchesBySha200ResponseResponseWithDefaults instantiates a new DescribeGitBranchesBySha200ResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeGitBranchesBySha200ResponseResponseWithDefaults() *DescribeGitBranchesBySha200ResponseResponse {
	this := DescribeGitBranchesBySha200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// GetRefs returns the Refs field value if set, zero value otherwise.
func (o *DescribeGitBranchesBySha200ResponseResponse) GetRefs() []RefInfo {
	if o == nil || utils.IsNil(o.Refs) {
		var ret []RefInfo
		return ret
	}
	return o.Refs
}

// GetRefsOk returns a tuple with the Refs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitBranchesBySha200ResponseResponse) GetRefsOk() ([]RefInfo, bool) {
	if o == nil || utils.IsNil(o.Refs) {
		return nil, false
	}
	return o.Refs, true
}

// HasRefs returns a boolean if a field has been set.
func (o *DescribeGitBranchesBySha200ResponseResponse) HasRefs() bool {
	if o != nil && !utils.IsNil(o.Refs) {
		return true
	}

	return false
}

// SetRefs gets a reference to the given []RefInfo and assigns it to the Refs field.
func (o *DescribeGitBranchesBySha200ResponseResponse) SetRefs(v []RefInfo) {
	o.Refs = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *DescribeGitBranchesBySha200ResponseResponse) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitBranchesBySha200ResponseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *DescribeGitBranchesBySha200ResponseResponse) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *DescribeGitBranchesBySha200ResponseResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o DescribeGitBranchesBySha200ResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeGitBranchesBySha200ResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Refs) {
		toSerialize["Refs"] = o.Refs
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["RequestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableDescribeGitBranchesBySha200ResponseResponse struct {
	value *DescribeGitBranchesBySha200ResponseResponse
	isSet bool
}

func (v NullableDescribeGitBranchesBySha200ResponseResponse) Get() *DescribeGitBranchesBySha200ResponseResponse {
	return v.value
}

func (v *NullableDescribeGitBranchesBySha200ResponseResponse) Set(val *DescribeGitBranchesBySha200ResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeGitBranchesBySha200ResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeGitBranchesBySha200ResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeGitBranchesBySha200ResponseResponse(val *DescribeGitBranchesBySha200ResponseResponse) *NullableDescribeGitBranchesBySha200ResponseResponse {
	return &NullableDescribeGitBranchesBySha200ResponseResponse{value: val, isSet: true}
}

func (v NullableDescribeGitBranchesBySha200ResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeGitBranchesBySha200ResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


