/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeMergeRequestLog200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeMergeRequestLog200Response{}

// DescribeMergeRequestLog200Response struct for DescribeMergeRequestLog200Response
type DescribeMergeRequestLog200Response struct {
	Response *DescribeMergeRequestLog200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeMergeRequestLog200Response instantiates a new DescribeMergeRequestLog200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeMergeRequestLog200Response() *DescribeMergeRequestLog200Response {
	this := DescribeMergeRequestLog200Response{}
	return &this
}

// NewDescribeMergeRequestLog200ResponseWithDefaults instantiates a new DescribeMergeRequestLog200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeMergeRequestLog200ResponseWithDefaults() *DescribeMergeRequestLog200Response {
	this := DescribeMergeRequestLog200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeMergeRequestLog200Response) GetResponse() DescribeMergeRequestLog200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeMergeRequestLog200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeMergeRequestLog200Response) GetResponseOk() (*DescribeMergeRequestLog200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeMergeRequestLog200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeMergeRequestLog200ResponseResponse and assigns it to the Response field.
func (o *DescribeMergeRequestLog200Response) SetResponse(v DescribeMergeRequestLog200ResponseResponse) {
	o.Response = &v
}

func (o DescribeMergeRequestLog200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeMergeRequestLog200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeMergeRequestLog200Response struct {
	value *DescribeMergeRequestLog200Response
	isSet bool
}

func (v NullableDescribeMergeRequestLog200Response) Get() *DescribeMergeRequestLog200Response {
	return v.value
}

func (v *NullableDescribeMergeRequestLog200Response) Set(val *DescribeMergeRequestLog200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeMergeRequestLog200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeMergeRequestLog200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeMergeRequestLog200Response(val *DescribeMergeRequestLog200Response) *NullableDescribeMergeRequestLog200Response {
	return &NullableDescribeMergeRequestLog200Response{value: val, isSet: true}
}

func (v NullableDescribeMergeRequestLog200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeMergeRequestLog200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


