/*
CODING OPEN API

  

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the ArtifactVersionFileBean type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ArtifactVersionFileBean{}

// ArtifactVersionFileBean 制品文件实体
type ArtifactVersionFileBean struct {
	// 文件名称
	Name *string `json:"Name,omitempty"`
	// 文件大小，单位：MB
	Size *float32 `json:"Size,omitempty"`
}

// NewArtifactVersionFileBean instantiates a new ArtifactVersionFileBean object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactVersionFileBean() *ArtifactVersionFileBean {
	this := ArtifactVersionFileBean{}
	var name string = ""
	this.Name = &name
	return &this
}

// NewArtifactVersionFileBeanWithDefaults instantiates a new ArtifactVersionFileBean object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactVersionFileBeanWithDefaults() *ArtifactVersionFileBean {
	this := ArtifactVersionFileBean{}
	var name string = ""
	this.Name = &name
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ArtifactVersionFileBean) GetName() string {
	if o == nil || utils.IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionFileBean) GetNameOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ArtifactVersionFileBean) HasName() bool {
	if o != nil && !utils.IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ArtifactVersionFileBean) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ArtifactVersionFileBean) GetSize() float32 {
	if o == nil || utils.IsNil(o.Size) {
		var ret float32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionFileBean) GetSizeOk() (*float32, bool) {
	if o == nil || utils.IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ArtifactVersionFileBean) HasSize() bool {
	if o != nil && !utils.IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given float32 and assigns it to the Size field.
func (o *ArtifactVersionFileBean) SetSize(v float32) {
	o.Size = &v
}

func (o ArtifactVersionFileBean) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactVersionFileBean) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !utils.IsNil(o.Size) {
		toSerialize["Size"] = o.Size
	}
	return toSerialize, nil
}

type NullableArtifactVersionFileBean struct {
	value *ArtifactVersionFileBean
	isSet bool
}

func (v NullableArtifactVersionFileBean) Get() *ArtifactVersionFileBean {
	return v.value
}

func (v *NullableArtifactVersionFileBean) Set(val *ArtifactVersionFileBean) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactVersionFileBean) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactVersionFileBean) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactVersionFileBean(val *ArtifactVersionFileBean) *NullableArtifactVersionFileBean {
	return &NullableArtifactVersionFileBean{value: val, isSet: true}
}

func (v NullableArtifactVersionFileBean) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactVersionFileBean) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


