/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the CreateGitCommitComment200ResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CreateGitCommitComment200ResponseResponse{}

// CreateGitCommitComment200ResponseResponse 公共返回体
type CreateGitCommitComment200ResponseResponse struct {
	Comment *CommitComment `json:"Comment,omitempty"`
	// 请求id
	RequestId *string `json:"RequestId,omitempty"`
}

// NewCreateGitCommitComment200ResponseResponse instantiates a new CreateGitCommitComment200ResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGitCommitComment200ResponseResponse() *CreateGitCommitComment200ResponseResponse {
	this := CreateGitCommitComment200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// NewCreateGitCommitComment200ResponseResponseWithDefaults instantiates a new CreateGitCommitComment200ResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGitCommitComment200ResponseResponseWithDefaults() *CreateGitCommitComment200ResponseResponse {
	this := CreateGitCommitComment200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *CreateGitCommitComment200ResponseResponse) GetComment() CommitComment {
	if o == nil || utils.IsNil(o.Comment) {
		var ret CommitComment
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGitCommitComment200ResponseResponse) GetCommentOk() (*CommitComment, bool) {
	if o == nil || utils.IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *CreateGitCommitComment200ResponseResponse) HasComment() bool {
	if o != nil && !utils.IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given CommitComment and assigns it to the Comment field.
func (o *CreateGitCommitComment200ResponseResponse) SetComment(v CommitComment) {
	o.Comment = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CreateGitCommitComment200ResponseResponse) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGitCommitComment200ResponseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreateGitCommitComment200ResponseResponse) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CreateGitCommitComment200ResponseResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o CreateGitCommitComment200ResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGitCommitComment200ResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Comment) {
		toSerialize["Comment"] = o.Comment
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["RequestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableCreateGitCommitComment200ResponseResponse struct {
	value *CreateGitCommitComment200ResponseResponse
	isSet bool
}

func (v NullableCreateGitCommitComment200ResponseResponse) Get() *CreateGitCommitComment200ResponseResponse {
	return v.value
}

func (v *NullableCreateGitCommitComment200ResponseResponse) Set(val *CreateGitCommitComment200ResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGitCommitComment200ResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGitCommitComment200ResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGitCommitComment200ResponseResponse(val *CreateGitCommitComment200ResponseResponse) *NullableCreateGitCommitComment200ResponseResponse {
	return &NullableCreateGitCommitComment200ResponseResponse{value: val, isSet: true}
}

func (v NullableCreateGitCommitComment200ResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGitCommitComment200ResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


