/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeGitMergeRequestsBySha200ResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeGitMergeRequestsBySha200ResponseResponse{}

// DescribeGitMergeRequestsBySha200ResponseResponse 公共返回体
type DescribeGitMergeRequestsBySha200ResponseResponse struct {
	// 合并请求详情
	Details []MergeRequestDetail `json:"Details,omitempty"`
	// 请求id
	RequestId *string `json:"RequestId,omitempty"`
}

// NewDescribeGitMergeRequestsBySha200ResponseResponse instantiates a new DescribeGitMergeRequestsBySha200ResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeGitMergeRequestsBySha200ResponseResponse() *DescribeGitMergeRequestsBySha200ResponseResponse {
	this := DescribeGitMergeRequestsBySha200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// NewDescribeGitMergeRequestsBySha200ResponseResponseWithDefaults instantiates a new DescribeGitMergeRequestsBySha200ResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeGitMergeRequestsBySha200ResponseResponseWithDefaults() *DescribeGitMergeRequestsBySha200ResponseResponse {
	this := DescribeGitMergeRequestsBySha200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) GetDetails() []MergeRequestDetail {
	if o == nil || utils.IsNil(o.Details) {
		var ret []MergeRequestDetail
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) GetDetailsOk() ([]MergeRequestDetail, bool) {
	if o == nil || utils.IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) HasDetails() bool {
	if o != nil && !utils.IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given []MergeRequestDetail and assigns it to the Details field.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) SetDetails(v []MergeRequestDetail) {
	o.Details = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *DescribeGitMergeRequestsBySha200ResponseResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o DescribeGitMergeRequestsBySha200ResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeGitMergeRequestsBySha200ResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Details) {
		toSerialize["Details"] = o.Details
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["RequestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableDescribeGitMergeRequestsBySha200ResponseResponse struct {
	value *DescribeGitMergeRequestsBySha200ResponseResponse
	isSet bool
}

func (v NullableDescribeGitMergeRequestsBySha200ResponseResponse) Get() *DescribeGitMergeRequestsBySha200ResponseResponse {
	return v.value
}

func (v *NullableDescribeGitMergeRequestsBySha200ResponseResponse) Set(val *DescribeGitMergeRequestsBySha200ResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeGitMergeRequestsBySha200ResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeGitMergeRequestsBySha200ResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeGitMergeRequestsBySha200ResponseResponse(val *DescribeGitMergeRequestsBySha200ResponseResponse) *NullableDescribeGitMergeRequestsBySha200ResponseResponse {
	return &NullableDescribeGitMergeRequestsBySha200ResponseResponse{value: val, isSet: true}
}

func (v NullableDescribeGitMergeRequestsBySha200ResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeGitMergeRequestsBySha200ResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


