/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DeletePoliciesById200ResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DeletePoliciesById200ResponseResponse{}

// DeletePoliciesById200ResponseResponse 公共返回体
type DeletePoliciesById200ResponseResponse struct {
	// 成功删除的权限组 ID
	DeletedPolicyId []int64 `json:"DeletedPolicyId,omitempty"`
	// 请求id
	RequestId *string `json:"RequestId,omitempty"`
}

// NewDeletePoliciesById200ResponseResponse instantiates a new DeletePoliciesById200ResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePoliciesById200ResponseResponse() *DeletePoliciesById200ResponseResponse {
	this := DeletePoliciesById200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// NewDeletePoliciesById200ResponseResponseWithDefaults instantiates a new DeletePoliciesById200ResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePoliciesById200ResponseResponseWithDefaults() *DeletePoliciesById200ResponseResponse {
	this := DeletePoliciesById200ResponseResponse{}
	var requestId string = "xxxxx"
	this.RequestId = &requestId
	return &this
}

// GetDeletedPolicyId returns the DeletedPolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeletePoliciesById200ResponseResponse) GetDeletedPolicyId() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.DeletedPolicyId
}

// GetDeletedPolicyIdOk returns a tuple with the DeletedPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeletePoliciesById200ResponseResponse) GetDeletedPolicyIdOk() ([]int64, bool) {
	if o == nil || utils.IsNil(o.DeletedPolicyId) {
		return nil, false
	}
	return o.DeletedPolicyId, true
}

// HasDeletedPolicyId returns a boolean if a field has been set.
func (o *DeletePoliciesById200ResponseResponse) HasDeletedPolicyId() bool {
	if o != nil && !utils.IsNil(o.DeletedPolicyId) {
		return true
	}

	return false
}

// SetDeletedPolicyId gets a reference to the given []int64 and assigns it to the DeletedPolicyId field.
func (o *DeletePoliciesById200ResponseResponse) SetDeletedPolicyId(v []int64) {
	o.DeletedPolicyId = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *DeletePoliciesById200ResponseResponse) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePoliciesById200ResponseResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *DeletePoliciesById200ResponseResponse) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *DeletePoliciesById200ResponseResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o DeletePoliciesById200ResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePoliciesById200ResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DeletedPolicyId != nil {
		toSerialize["DeletedPolicyId"] = o.DeletedPolicyId
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["RequestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableDeletePoliciesById200ResponseResponse struct {
	value *DeletePoliciesById200ResponseResponse
	isSet bool
}

func (v NullableDeletePoliciesById200ResponseResponse) Get() *DeletePoliciesById200ResponseResponse {
	return v.value
}

func (v *NullableDeletePoliciesById200ResponseResponse) Set(val *DeletePoliciesById200ResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePoliciesById200ResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePoliciesById200ResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePoliciesById200ResponseResponse(val *DeletePoliciesById200ResponseResponse) *NullableDeletePoliciesById200ResponseResponse {
	return &NullableDeletePoliciesById200ResponseResponse{value: val, isSet: true}
}

func (v NullableDeletePoliciesById200ResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePoliciesById200ResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


