/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeCodingCIBuild200Response type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeCodingCIBuild200Response{}

// DescribeCodingCIBuild200Response struct for DescribeCodingCIBuild200Response
type DescribeCodingCIBuild200Response struct {
	Response *DescribeCodingCIBuild200ResponseResponse `json:"Response,omitempty"`
}

// NewDescribeCodingCIBuild200Response instantiates a new DescribeCodingCIBuild200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeCodingCIBuild200Response() *DescribeCodingCIBuild200Response {
	this := DescribeCodingCIBuild200Response{}
	return &this
}

// NewDescribeCodingCIBuild200ResponseWithDefaults instantiates a new DescribeCodingCIBuild200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeCodingCIBuild200ResponseWithDefaults() *DescribeCodingCIBuild200Response {
	this := DescribeCodingCIBuild200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *DescribeCodingCIBuild200Response) GetResponse() DescribeCodingCIBuild200ResponseResponse {
	if o == nil || utils.IsNil(o.Response) {
		var ret DescribeCodingCIBuild200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeCodingCIBuild200Response) GetResponseOk() (*DescribeCodingCIBuild200ResponseResponse, bool) {
	if o == nil || utils.IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *DescribeCodingCIBuild200Response) HasResponse() bool {
	if o != nil && !utils.IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given DescribeCodingCIBuild200ResponseResponse and assigns it to the Response field.
func (o *DescribeCodingCIBuild200Response) SetResponse(v DescribeCodingCIBuild200ResponseResponse) {
	o.Response = &v
}

func (o DescribeCodingCIBuild200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeCodingCIBuild200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	return toSerialize, nil
}

type NullableDescribeCodingCIBuild200Response struct {
	value *DescribeCodingCIBuild200Response
	isSet bool
}

func (v NullableDescribeCodingCIBuild200Response) Get() *DescribeCodingCIBuild200Response {
	return v.value
}

func (v *NullableDescribeCodingCIBuild200Response) Set(val *DescribeCodingCIBuild200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeCodingCIBuild200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeCodingCIBuild200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeCodingCIBuild200Response(val *DescribeCodingCIBuild200Response) *NullableDescribeCodingCIBuild200Response {
	return &NullableDescribeCodingCIBuild200Response{value: val, isSet: true}
}

func (v NullableDescribeCodingCIBuild200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeCodingCIBuild200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


