/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the DescribeGitCommitDiffRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DescribeGitCommitDiffRequest{}

// DescribeGitCommitDiffRequest struct for DescribeGitCommitDiffRequest
type DescribeGitCommitDiffRequest struct {
	// 仓库id
	DepotId int64 `json:"DepotId"`
	// 仓库路径，DepotId与DepotPath二选一即可
	DepotPath *string `json:"DepotPath,omitempty"`
	// 查询指定文件时填写
	Path *string `json:"Path,omitempty"`
	// 提交id
	Sha string `json:"Sha"`
}

type _DescribeGitCommitDiffRequest DescribeGitCommitDiffRequest

// NewDescribeGitCommitDiffRequest instantiates a new DescribeGitCommitDiffRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeGitCommitDiffRequest(depotId int64, sha string) *DescribeGitCommitDiffRequest {
	this := DescribeGitCommitDiffRequest{}
	this.DepotId = depotId
	this.Sha = sha
	return &this
}

// NewDescribeGitCommitDiffRequestWithDefaults instantiates a new DescribeGitCommitDiffRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeGitCommitDiffRequestWithDefaults() *DescribeGitCommitDiffRequest {
	this := DescribeGitCommitDiffRequest{}
	return &this
}

// GetDepotId returns the DepotId field value
func (o *DescribeGitCommitDiffRequest) GetDepotId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DepotId
}

// GetDepotIdOk returns a tuple with the DepotId field value
// and a boolean to check if the value has been set.
func (o *DescribeGitCommitDiffRequest) GetDepotIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepotId, true
}

// SetDepotId sets field value
func (o *DescribeGitCommitDiffRequest) SetDepotId(v int64) {
	o.DepotId = v
}

// GetDepotPath returns the DepotPath field value if set, zero value otherwise.
func (o *DescribeGitCommitDiffRequest) GetDepotPath() string {
	if o == nil || utils.IsNil(o.DepotPath) {
		var ret string
		return ret
	}
	return *o.DepotPath
}

// GetDepotPathOk returns a tuple with the DepotPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitCommitDiffRequest) GetDepotPathOk() (*string, bool) {
	if o == nil || utils.IsNil(o.DepotPath) {
		return nil, false
	}
	return o.DepotPath, true
}

// HasDepotPath returns a boolean if a field has been set.
func (o *DescribeGitCommitDiffRequest) HasDepotPath() bool {
	if o != nil && !utils.IsNil(o.DepotPath) {
		return true
	}

	return false
}

// SetDepotPath gets a reference to the given string and assigns it to the DepotPath field.
func (o *DescribeGitCommitDiffRequest) SetDepotPath(v string) {
	o.DepotPath = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *DescribeGitCommitDiffRequest) GetPath() string {
	if o == nil || utils.IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeGitCommitDiffRequest) GetPathOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *DescribeGitCommitDiffRequest) HasPath() bool {
	if o != nil && !utils.IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *DescribeGitCommitDiffRequest) SetPath(v string) {
	o.Path = &v
}

// GetSha returns the Sha field value
func (o *DescribeGitCommitDiffRequest) GetSha() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sha
}

// GetShaOk returns a tuple with the Sha field value
// and a boolean to check if the value has been set.
func (o *DescribeGitCommitDiffRequest) GetShaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sha, true
}

// SetSha sets field value
func (o *DescribeGitCommitDiffRequest) SetSha(v string) {
	o.Sha = v
}

func (o DescribeGitCommitDiffRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeGitCommitDiffRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["DepotId"] = o.DepotId
	if !utils.IsNil(o.DepotPath) {
		toSerialize["DepotPath"] = o.DepotPath
	}
	if !utils.IsNil(o.Path) {
		toSerialize["Path"] = o.Path
	}
	toSerialize["Sha"] = o.Sha
	return toSerialize, nil
}

func (o *DescribeGitCommitDiffRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"DepotId",
		"Sha",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDescribeGitCommitDiffRequest := _DescribeGitCommitDiffRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDescribeGitCommitDiffRequest)

	if err != nil {
		return err
	}

	*o = DescribeGitCommitDiffRequest(varDescribeGitCommitDiffRequest)

	return err
}

type NullableDescribeGitCommitDiffRequest struct {
	value *DescribeGitCommitDiffRequest
	isSet bool
}

func (v NullableDescribeGitCommitDiffRequest) Get() *DescribeGitCommitDiffRequest {
	return v.value
}

func (v *NullableDescribeGitCommitDiffRequest) Set(val *DescribeGitCommitDiffRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeGitCommitDiffRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeGitCommitDiffRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeGitCommitDiffRequest(val *DescribeGitCommitDiffRequest) *NullableDescribeGitCommitDiffRequest {
	return &NullableDescribeGitCommitDiffRequest{value: val, isSet: true}
}

func (v NullableDescribeGitCommitDiffRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeGitCommitDiffRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


