/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the ModifyServiceHookRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ModifyServiceHookRequest{}

// ModifyServiceHookRequest struct for ModifyServiceHookRequest
type ModifyServiceHookRequest struct {
	// 发送方式属性
	ActionProperty string `json:"ActionProperty"`
	// 事件开关
	Enabled bool `json:"Enabled"`
	// 事件名，取值范围：ITERATION_CREATED,ITERATION_DELETED,ITERATION_UPDATED,ISSUE_CREATED,ISSUE_DELETED,ISSUE_COMMENT_CREATED,ISSUE_STATUS_UPDATED,ISSUE_ASSIGNEE_CHANGED,ISSUE_ITERATION_CHANGED,ISSUE_RELATIONSHIP_CHANGED,ISSUE_UPDATED,GIT_PUSHED,GIT_MR_CREATED,GIT_MR_UPDATED,GIT_MR_MERGED,GIT_MR_CLOSED,ARTIFACTS_VERSION_CREATED,ARTIFACTS_VERSION_UPDATED,ARTIFACTS_VERSION_DOWNLOADED,ARTIFACTS_VERSION_DELETED,ARTIFACTS_VERSION_RELEASED,ARTIFACTS_VERSION_DOWNLOAD_FORBIDDEN,ARTIFACTS_VERSION_DOWNLOAD_ALLOWED,ARTIFACTS_VERSION_DOWNLOAD_BLOCKED,ARTIFACTS_REPO_CREATED,ARTIFACTS_REPO_UPDATED,ARTIFACTS_REPO_DELETED,CI_JOB_CREATED,CI_JOB_UPDATED,CI_JOB_DELETED,CI_JOB_STARTED,CI_JOB_FINISHED,FILE_CREATED,FILE_UPDATED,FILE_RENAMED,FILE_SHARE_UPDATED,FILE_MOVED,FILE_COPIED,FILE_MOVED_TO_RECYCLE_BIN,FILE_RESTORED_FROM_RECYCLE_BIN,FILE_DELETED,WIKI_CREATED,WIKI_UPDATED,WIKI_MOVED,WIKI_SHARE_UPDATED,WIKI_ACCESS_UPDATED,WIKI_COPIED,WIKI_MOVED_TO_RECYCLE_BIN,WIKI_RESTORED_FROM_RECYCLE_BIN,WIKI_DELETED,MEMBER_CREATED,MEMBER_DELETED,MEMBER_ROLE_UPDATED,TEST_PLAN_CREATED, TEST_PLAN_UPDATED, TEST_PLAN_FINISHED, TEST_TASK_ASSIGNED, TEST_REPORT_CREATED, FLEXIBLE_TESTX_REVIEW_CREATED, FLEXIBLE_TESTX_REVIEW_COMMENTED, FLEXIBLE_TESTX_REVIEW_UPDATED, FLEXIBLE_TESTX_REVIEW_COMPLETED, FLEXIBLE_TESTX_PLAN_CREATED, FLEXIBLE_TESTX_PLAN_TASK_ASSIGNED, FLEXIBLE_TESTX_PLAN_UPDATED, FLEXIBLE_TESTX_PLAN_FINISHED, FLEXIBLE_TESTX_REPORT_CREATED, CODE_DOG_CREATE_JOB, CODE_DOG_RESULT_NOTIFY, PLAN_CREATED, PLAN_DELETED, PLAN_COMMENT_CREATED, PLAN_STATUE_CHANGED, PLAN_ASSIGNEE_CHANGED, PLAN_UPDATED, RISK_CREATED, RISK_DELETED, RISK_COMMENT_CREATED, RISK_STATUS_CHANGED, RISK_ASSIGNEE_CHANGED, RISK_UPDATED
	Event []string `json:"Event"`
	// 过滤器属性
	FilterProperty string `json:"FilterProperty"`
	// Service Hook 编号
	Id string `json:"Id"`
	// 备注名
	Name *string `json:"Name,omitempty"`
	// 项目编号或者研发空间编号
	ProjectId int64 `json:"ProjectId"`
	// 服务名，取值范围：WebHook、WeCom、DingDing、Jenkins、FeiShu。
	Service string `json:"Service"`
	// 发送方式，取值范围：dingding_group_chat_robot,wecom_group_chat_robot,jenkins_generic_build_job,feishu_group_chat_robot,webhook_http_post,webhook_http_get
	ServiceAction string `json:"ServiceAction"`
	// 目标数据类型：PROJECT,SPACE_NODE,PROGRAM,默认PROJECT
	TargetType *string `json:"TargetType,omitempty"`
}

type _ModifyServiceHookRequest ModifyServiceHookRequest

// NewModifyServiceHookRequest instantiates a new ModifyServiceHookRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyServiceHookRequest(actionProperty string, enabled bool, event []string, filterProperty string, id string, projectId int64, service string, serviceAction string) *ModifyServiceHookRequest {
	this := ModifyServiceHookRequest{}
	this.ActionProperty = actionProperty
	this.Enabled = enabled
	this.Event = event
	this.FilterProperty = filterProperty
	this.Id = id
	this.ProjectId = projectId
	this.Service = service
	this.ServiceAction = serviceAction
	return &this
}

// NewModifyServiceHookRequestWithDefaults instantiates a new ModifyServiceHookRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyServiceHookRequestWithDefaults() *ModifyServiceHookRequest {
	this := ModifyServiceHookRequest{}
	return &this
}

// GetActionProperty returns the ActionProperty field value
func (o *ModifyServiceHookRequest) GetActionProperty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActionProperty
}

// GetActionPropertyOk returns a tuple with the ActionProperty field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetActionPropertyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionProperty, true
}

// SetActionProperty sets field value
func (o *ModifyServiceHookRequest) SetActionProperty(v string) {
	o.ActionProperty = v
}

// GetEnabled returns the Enabled field value
func (o *ModifyServiceHookRequest) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ModifyServiceHookRequest) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEvent returns the Event field value
func (o *ModifyServiceHookRequest) GetEvent() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetEventOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Event, true
}

// SetEvent sets field value
func (o *ModifyServiceHookRequest) SetEvent(v []string) {
	o.Event = v
}

// GetFilterProperty returns the FilterProperty field value
func (o *ModifyServiceHookRequest) GetFilterProperty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilterProperty
}

// GetFilterPropertyOk returns a tuple with the FilterProperty field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetFilterPropertyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterProperty, true
}

// SetFilterProperty sets field value
func (o *ModifyServiceHookRequest) SetFilterProperty(v string) {
	o.FilterProperty = v
}

// GetId returns the Id field value
func (o *ModifyServiceHookRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ModifyServiceHookRequest) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModifyServiceHookRequest) GetName() string {
	if o == nil || utils.IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetNameOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModifyServiceHookRequest) HasName() bool {
	if o != nil && !utils.IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModifyServiceHookRequest) SetName(v string) {
	o.Name = &v
}

// GetProjectId returns the ProjectId field value
func (o *ModifyServiceHookRequest) GetProjectId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetProjectIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ModifyServiceHookRequest) SetProjectId(v int64) {
	o.ProjectId = v
}

// GetService returns the Service field value
func (o *ModifyServiceHookRequest) GetService() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetServiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *ModifyServiceHookRequest) SetService(v string) {
	o.Service = v
}

// GetServiceAction returns the ServiceAction field value
func (o *ModifyServiceHookRequest) GetServiceAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceAction
}

// GetServiceActionOk returns a tuple with the ServiceAction field value
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetServiceActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAction, true
}

// SetServiceAction sets field value
func (o *ModifyServiceHookRequest) SetServiceAction(v string) {
	o.ServiceAction = v
}

// GetTargetType returns the TargetType field value if set, zero value otherwise.
func (o *ModifyServiceHookRequest) GetTargetType() string {
	if o == nil || utils.IsNil(o.TargetType) {
		var ret string
		return ret
	}
	return *o.TargetType
}

// GetTargetTypeOk returns a tuple with the TargetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyServiceHookRequest) GetTargetTypeOk() (*string, bool) {
	if o == nil || utils.IsNil(o.TargetType) {
		return nil, false
	}
	return o.TargetType, true
}

// HasTargetType returns a boolean if a field has been set.
func (o *ModifyServiceHookRequest) HasTargetType() bool {
	if o != nil && !utils.IsNil(o.TargetType) {
		return true
	}

	return false
}

// SetTargetType gets a reference to the given string and assigns it to the TargetType field.
func (o *ModifyServiceHookRequest) SetTargetType(v string) {
	o.TargetType = &v
}

func (o ModifyServiceHookRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyServiceHookRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ActionProperty"] = o.ActionProperty
	toSerialize["Enabled"] = o.Enabled
	toSerialize["Event"] = o.Event
	toSerialize["FilterProperty"] = o.FilterProperty
	toSerialize["Id"] = o.Id
	if !utils.IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	toSerialize["ProjectId"] = o.ProjectId
	toSerialize["Service"] = o.Service
	toSerialize["ServiceAction"] = o.ServiceAction
	if !utils.IsNil(o.TargetType) {
		toSerialize["TargetType"] = o.TargetType
	}
	return toSerialize, nil
}

func (o *ModifyServiceHookRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ActionProperty",
		"Enabled",
		"Event",
		"FilterProperty",
		"Id",
		"ProjectId",
		"Service",
		"ServiceAction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModifyServiceHookRequest := _ModifyServiceHookRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModifyServiceHookRequest)

	if err != nil {
		return err
	}

	*o = ModifyServiceHookRequest(varModifyServiceHookRequest)

	return err
}

type NullableModifyServiceHookRequest struct {
	value *ModifyServiceHookRequest
	isSet bool
}

func (v NullableModifyServiceHookRequest) Get() *ModifyServiceHookRequest {
	return v.value
}

func (v *NullableModifyServiceHookRequest) Set(val *ModifyServiceHookRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyServiceHookRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyServiceHookRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyServiceHookRequest(val *ModifyServiceHookRequest) *NullableModifyServiceHookRequest {
	return &NullableModifyServiceHookRequest{value: val, isSet: true}
}

func (v NullableModifyServiceHookRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyServiceHookRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


