/*
CODING OPEN API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"; "github.com/mindfocus/coding-sdk/utils"
)

// checks if the ModifyProjectAnnouncementRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ModifyProjectAnnouncementRequest{}

// ModifyProjectAnnouncementRequest struct for ModifyProjectAnnouncementRequest
type ModifyProjectAnnouncementRequest struct {
	// 项目名
	ProjectName string `json:"ProjectName"`
	// 公告内容
	Content string `json:"Content"`
	// 公告id
	Id int64 `json:"Id"`
}

type _ModifyProjectAnnouncementRequest ModifyProjectAnnouncementRequest

// NewModifyProjectAnnouncementRequest instantiates a new ModifyProjectAnnouncementRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyProjectAnnouncementRequest(projectName string, content string, id int64) *ModifyProjectAnnouncementRequest {
	this := ModifyProjectAnnouncementRequest{}
	this.ProjectName = projectName
	this.Content = content
	this.Id = id
	return &this
}

// NewModifyProjectAnnouncementRequestWithDefaults instantiates a new ModifyProjectAnnouncementRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyProjectAnnouncementRequestWithDefaults() *ModifyProjectAnnouncementRequest {
	this := ModifyProjectAnnouncementRequest{}
	var projectName string = ""
	this.ProjectName = projectName
	var content string = ""
	this.Content = content
	var id int64 = 0
	this.Id = id
	return &this
}

// GetProjectName returns the ProjectName field value
func (o *ModifyProjectAnnouncementRequest) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *ModifyProjectAnnouncementRequest) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *ModifyProjectAnnouncementRequest) SetProjectName(v string) {
	o.ProjectName = v
}

// GetContent returns the Content field value
func (o *ModifyProjectAnnouncementRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ModifyProjectAnnouncementRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ModifyProjectAnnouncementRequest) SetContent(v string) {
	o.Content = v
}

// GetId returns the Id field value
func (o *ModifyProjectAnnouncementRequest) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ModifyProjectAnnouncementRequest) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ModifyProjectAnnouncementRequest) SetId(v int64) {
	o.Id = v
}

func (o ModifyProjectAnnouncementRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyProjectAnnouncementRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ProjectName"] = o.ProjectName
	toSerialize["Content"] = o.Content
	toSerialize["Id"] = o.Id
	return toSerialize, nil
}

func (o *ModifyProjectAnnouncementRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ProjectName",
		"Content",
		"Id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModifyProjectAnnouncementRequest := _ModifyProjectAnnouncementRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModifyProjectAnnouncementRequest)

	if err != nil {
		return err
	}

	*o = ModifyProjectAnnouncementRequest(varModifyProjectAnnouncementRequest)

	return err
}

type NullableModifyProjectAnnouncementRequest struct {
	value *ModifyProjectAnnouncementRequest
	isSet bool
}

func (v NullableModifyProjectAnnouncementRequest) Get() *ModifyProjectAnnouncementRequest {
	return v.value
}

func (v *NullableModifyProjectAnnouncementRequest) Set(val *ModifyProjectAnnouncementRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyProjectAnnouncementRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyProjectAnnouncementRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyProjectAnnouncementRequest(val *ModifyProjectAnnouncementRequest) *NullableModifyProjectAnnouncementRequest {
	return &NullableModifyProjectAnnouncementRequest{value: val, isSet: true}
}

func (v NullableModifyProjectAnnouncementRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyProjectAnnouncementRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


